name: mapeo_terrenos_rt
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.0
  permission_handler: ^12.0.1
  geolocator: ^14.0.2
  url_launcher: ^6.3.0
  flutter_dotenv: ^5.1.0
  # Dependencias Añadidas
  google_maps_flutter: ^2.6.1
  google_maps_flutter_web: ^0.5.12+2
  uuid: ^4.2.1
  intl: ^0.20.2
  location: ^8.0.1
  flutter_foreground_task: ^9.1.0
  device_info_plus: ^11.5.0
  background_locator_2: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/.env
    - assets/icon.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"